
# ================= 数据库配置 =================
project:
  project_type: "fullstack" #frontend/backend/fullstack
  database_url: "localhost"
  database_type: "mysql"
  database_port: 3306
  database_username: "root"
  database_password: "123456"
  database_table: "test"
  frontend_framework: ""
  backend_framework: "fastapi"
  backend_language: "python"